spring:
  application:
    name: taskify

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_TASKIFY_DB_NAME}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signature-private-key: ${TASKIFY_JWT_SIGNATURE_PRIVATE_KEY}
  signature-public-key: ${TASKIFY_JWT_SIGNATURE_PUBLIC_KEY}
  expiration: ${TASKIFY_JWT_EXPIRATION_TIME_MILLISECONDS}